{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "w7panel-cloudconfig.fullname" . }}
  labels:
    {{- include "w7panel-cloudconfig.labels" . | nindent 4 }}
rules:
  - apiGroups: ["cloudconfig.w7.cc"]
    resources: ["cloudconfigs", "cloudconfigs/status", "cloudconfigs/finalizers"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "patch", "update", "watch"]
  - apiGroups: [""]
    resources: ["configmaps", "pods", "namespaces"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
{{- end }}
