{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "w7panel-cloudconfig.serviceAccountName" . }}
  labels:
    {{- include "w7panel-cloudconfig.labels" . | nindent 4 }}
{{- end }}
