replicaCount: 1

image:
  repository: ghcr.registry.cdn.w7.cc/w7panel/w7panel-cloudconfig
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

service:
  port: 8002

metrics:
  port: 18080

health:
  port: 8081

oidc:
  discoveryURL: http://w7panel-offline.default.svc:8000/panel-api/v1/oidc/.well-known/openid-configuration
  clientID: default
  redirectURL: http://127.0.0.1:3000/callback

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
